---
title: "p8105_hw5_lh3109"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
```


# Probelm 1
From Office Hour

## Tidy data
```{r}
homicide_df = 
  #load and clean data
  read_csv("./data/homicide-data.csv", na = c("", "Unkown")) %>% 
  mutate(
    #create a new variable: city_state
    city_state = str_c(city, state),
    #create a new variable: resolution
    resolution = case_when(
      disposition == "Closed without arrest" ~ "unsolved",
      disposition == "Open/No arrest" ~ "unsolved",
      disposition == "Closed by arrest" ~ "solved"
    )) %>% 
  #change column position
  relocate(city_state) %>% 
  #filter out data entry error
  filter(city_state != "TulsaAL")
```

Describe the raw data

## Baltimore, MD
```{r}
#load data
baltimore_df = 
  homicide_df %>% 
  #filter data from Baltimore, MD
  filter(city_state == "BaltimoreMD")

baltimore_summary = 
  baltimore_df %>% 
  #summarize data
  summarize(
    #sum number pf unsolved homocides
    unsolved = sum(resolution == "unsolved"),
    #sum number of rows
    n = n()
  )

#perform proportion test
baltimore_test = 
  prop.test(x = baltimore_summary %>%  pull(unsolved),
          n = baltimore_summary %>%  pull(n))

#convert the test result to a better workable format
baltimore_test %>% 
  broom::tidy()
```

## Iteration
write a function
```{r}
prop_test_function = function(city_df) {
  #summarize data
  city_summary = 
    city_df %>% 
    summarize(
      #sum number pf unsolved homicides
      unsolved = sum(resolution == "unsolved"),
      #sum number of rows
      n = n()
      )
  
  #perform statistical test
  city_test = 
  prop.test(
    x = city_summary %>%  pull(unsolved),
    n = city_summary %>%  pull(n))
  
  #return
  return(city_test)
}

prop_test_function(baltimore_df)

#test the function
homicide_df %>% 
  filter(city_state == "AlbuquerqueNM") %>% 
  prop_test_function()
```

iterate across all cities
```{r}
result_df = 
  homicide_df %>% 
  #nest the data frame
  nest(data = uid:resolution) %>% 
  #create new variables that store the test results
  mutate(
    test_results = map(data, prop_test_function),
    tidy_results = map(test_results, broom::tidy)
  ) %>% 
  select(city_state, tidy_results) %>% 
  #unnest data set
  unnest(tidy_results) %>% 
  select(city_state, estimate, starts_with("conf"))

#test results
#nest_df %>% 
  #filter(city_state == "BaltimoreMD") %>% 
  #pull(tidy_results)
```

A plot showing estimate and confidence interval
```{r}
result_df %>% 
  #arrange the data
  mutate(city_state = fct_reorder(city_state, estimate)) %>% 
  #create plot
  ggplot(aes(x = city_state, y = estimate)) + 
  geom_point() + 
  #add error bar
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high)) +
  #adjust labels on x axis
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))
```

Another way for problem 1...
```{r}
homicide_df %>% 
  group_by(city_state) %>% 
  summarize(
    unsolved = sum(resolution == "unsolved"),
    n = n()
  ) %>% 
  mutate(
    #mapping two columns at the same time
    test_results = map2(unsolved, n, prop.test),
    tidy_results = map(test_results, broom::tidy)
  ) %>% 
  select(city_state, tidy_results) %>% 
  #unnest data set
  unnest(tidy_results) %>% 
  select(city_state, estimate, starts_with("conf"))
```



# Problem 2


# Problem 3

